const PDFDocument = require("pdfkit");

function generateCertificatePdf({ attempt, quiz, user }) {
  const doc = new PDFDocument({ size: "A4", layout: "landscape", margin: 56 });
  const issuedAt = new Date();
  const verificationId = String(attempt._id);

  doc.rect(24, 24, 794, 547).lineWidth(2).stroke("#2563eb");
  doc.rect(36, 36, 770, 523).lineWidth(1).stroke("#f59e0b");

  doc
    .fontSize(18)
    .fillColor("#2563eb")
    .text("Quivora Certificate", { align: "center" })
    .moveDown(1.2);

  doc.fontSize(38).fillColor("#111827").text("Certificate of Completion", { align: "center" });
  doc.moveDown(1);
  doc.fontSize(16).fillColor("#374151").text("This certifies that", { align: "center" });
  doc.moveDown(0.4);
  doc.fontSize(32).fillColor("#111827").text(user?.name || "Participant", { align: "center" });
  doc.moveDown(0.5);
  doc.fontSize(16).fillColor("#374151").text("successfully completed", { align: "center" });
  doc.moveDown(0.4);
  doc.fontSize(26).fillColor("#111827").text(quiz.title, { align: "center" });
  doc.moveDown(1);
  doc.fontSize(18).fillColor("#111827").text(`Score: ${attempt.score || 0} points`, { align: "center" });
  doc.moveDown(1.5);

  doc.fontSize(11).fillColor("#4b5563");
  doc.text(`Issued: ${issuedAt.toLocaleDateString("en-US")}`, 90, 470);
  doc.text(`Verification ID: ${verificationId}`, 90, 490);
  doc.text("Generated by Quivora", 590, 490, { align: "right" });

  return doc;
}

module.exports = { generateCertificatePdf };
